server:
  port: 8703

spring:
  application:
    name: client3 # 应用名称，会在Eureka中显示

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:8700/eureka
    register-with-eureka: true #服务启动方启动时，会检测该参数是否为true，true会注册给eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
